version: 1
formatters:
  default: 
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'

handlers:
  timed_file:
    class: logging.handlers.TimedRotatingFileHandler
    formatter: default
    filename: '()'
    when: 'D'
    interval: 1
    backupCount: 7
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: default    

root:
  level: INFO
  handlers: [console]