version: 1
formatters:
  default: 
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'

handlers:
  timed_file:
    class: logging.handlers.TimedRotatingFileHandler
    formatter: default
    when: 'D'
    interval: 1
    backupCount: 7
    level: DEBUG
    filename: 'default.log'
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: default    

root:
  level: DEBUG
  handlers: [console, timed_file]